# Site settings
title: EXPLODE THE CODE
header-img: img/home-bg.png
email: oconnojb@gmail.com
copyright_name: oconnojb
description: > # this means to ignore newlines until "baseurl:"
  learning to talk to computers
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  oconnojb
learn_profile: oconnojb
email_username: oconnojb@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
